## Initial Setup

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from tools import *
import pandas as pd
import numpy as np
import datetime as dt

In [30]:
activities = pd.read_csv("data/activities.csv")
activities[(activities.HAS_ACCURATE_LAPS == 0.5) | (activities.HAS_ACCURATE_LAPS == 1.0)]

,Activity ID,Activity Date,Activity Name,IS_TRACK_WORKOUT,HAS_ACCURATE_LAPS,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,...,"<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.total_grit"">Total Grit</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_flow"">Avg Flow</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.flagged"">Flagged</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_elapsed_speed"">Avg Elapsed Speed</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.dirt_distance"">Dirt Distance</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.newly_explored_distance"">Newly Explored Distance</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.newly_explored_dirt_distance"">Newly Explored Dirt Distance</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.sport_type"">Sport Type</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.total_steps"">Total Steps</span>",Media
794,2079581725,"Jan 15, 2019, 5:06:37 AM",Track Session,1.0,0.5,Run,"2*(600m, 30s rest then 200m) 1:41, 1:42, 1:40 ...",2999,6.95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,2147844352,"Feb 12, 2019, 3:14:17 AM",Track session,1.0,0.5,Run,"3*(600m then 200m with 30 second rest), 1:44, ...",4275,8.03,189.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
827,2147845716,"Feb 14, 2019, 4:09:26 AM",Track session,1.0,1.0,Run,"5*300m (47,50,49,47,45) then 6*200m (28,30,28,...",3763,9.04,188.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,2159452990,"Feb 16, 2019, 11:50:55 PM",800m Southland Club Champs,1.0,1.0,Run,"2:07, still very windy",5988,7.95,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,2164067134,"Feb 21, 2019, 4:07:26 AM",Track session,1.0,0.5,Run,"12 min tempo at 3:40 pace, then 4*90sec interv...",3779,9.99,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2052,8408655136,"Jan 17, 2023, 7:39:56 PM",Track,1.0,1.0,Run,400’s at 63,4249,9.49,187.0,...,NaN,NaN,0.0,2.235399,2023.099976,NaN,NaN,NaN,7954.0,NaN
2054,8416098869,"Jan 19, 2023, 7:41:15 AM",200’s,1.0,1.0,Run,NaN,3855,10.10,189.0,...,NaN,NaN,0.0,2.620519,7972.100098,NaN,NaN,NaN,7864.0,NaN
2059,8446286759,"Jan 24, 2023, 7:43:37 PM",600’s,1.0,1.0,Run,Not so good,4037,7.84,182.0,...,NaN,NaN,0.0,1.941910,2028.699951,NaN,NaN,NaN,6890.0,NaN
2073,8522903907,"Feb 7, 2023, 7:40:09 PM",200’s,1.0,1.0,Run,NaN,3479,8.22,187.0,...,NaN,NaN,0.0,2.364361,1102.800049,NaN,NaN,NaN,6810.0,NaN
2085,8594860256,"Feb 20, 2023, 7:38:08 PM",200’s,1.0,1.0,Run,NaN,3667,8.09,181.0,...,NaN,NaN,0.0,2.206575,56.500000,NaN,NaN,NaN,6732.0,NaN

,Activity ID,Activity Date,Activity Name,IS_TRACK_WORKOUT,HAS_ACCURATE_LAPS,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,...,"<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.total_grit"">Total Grit</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_flow"">Avg Flow</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.flagged"">Flagged</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.avg_elapsed_speed"">Avg Elapsed Speed</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.dirt_distance"">Dirt Distance</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.newly_explored_distance"">Newly Explored Distance</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.newly_explored_dirt_distance"">Newly Explored Dirt Distance</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.sport_type"">Sport Type</span>","<span class=""translation_missing"" title=""translation missing: en-US.lib.export.portability_exporter.activities.horton_values.total_steps"">Total Steps</span>",Media
0,440532314,"Nov 28, 2015, 2:14:09 AM",Quick Jog,NaN,NaN,Run,Slow jog in the rain until I found that the pa...,514,1.91,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,441175376,"Nov 28, 2015, 9:06:08 PM",Routeburn,NaN,NaN,Run,"First time doing the routeburn, and first time...",17248,31.15,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,442309961,"Dec 1, 2015, 2:45:06 AM",Intervally thing,NaN,NaN,Run,"First lap at 5:00/km pace-ish, 2nd and 3rd at ...",2002,7.22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,445839488,"Dec 3, 2015, 2:43:58 AM",Hill Reps around Fryer Street,NaN,NaN,Run,4 hill reps near Fryer Street.,857,2.88,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,445839590,"Dec 4, 2015, 9:06:00 PM",Run up the Skyline,NaN,NaN,Run,From the house up the Skyline for a Ledge Swin...,1950,3.77,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,2355593218,"May 10, 2019, 4:08:35 AM",Easy jog up the Ben Lomond track,0.0,NaN,Run,NaN,5975,9.60,194.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,2371508021,"May 11, 2019, 5:38:14 AM",Hill reps,0.0,NaN,Run,*10,2633,6.98,159.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,2371508277,"May 13, 2019, 7:49:04 AM",Easy jog,0.0,NaN,Run,NaN,1352,3.36,179.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,2371509360,"May 15, 2019, 12:57:08 AM",Southland XC,0.0,NaN,Run,"3rd, a bit of asthma.",5194,9.87,195.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,2371509837,"May 16, 2019, 4:34:21 AM",Easy jog up Queenstown Hill,0.0,NaN,Run,NaN,3689,8.37,188.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
points, laps = read_activity("data/activities/run-20190115T180637.fit")
laps

,Timestamp,start_pos_lat,start_pos_long,end_pos_lat,end_pos_long,total_timer_time,total_distance,avg_speed,lap_time,lap_distance,start_x,start_y,end_x,end_y
0,2019-01-15 05:08:17+00:00,-45.015371,168.735242,-45.016246,168.734682,NaN,NaN,6.07,101.0,612.91,NaN,-2867929.285486,NaN,-2867985.030899
1,2019-01-15 05:08:48+00:00,-45.016289,168.734703,-45.016306,168.734741,NaN,NaN,1.14,31.0,35.37,NaN,-2867987.770376,NaN,-2867988.854419
2,2019-01-15 05:09:19+00:00,-45.016307,168.734758,-45.01538,168.735303,NaN,NaN,6.22,31.0,192.93,NaN,-2867988.9185,NaN,-2867929.862218
3,2019-01-15 05:14:20+00:00,-45.015328,168.735277,-45.015357,168.735242,NaN,NaN,1.75,301.0,525.53,NaN,-2867926.546009,NaN,-2867928.393687
4,2019-01-15 05:16:02+00:00,-45.015344,168.735232,-45.016255,168.734691,NaN,NaN,6.0,102.0,611.76,NaN,-2867927.56597,NaN,-2867985.607631
5,2019-01-15 05:16:35+00:00,-45.016293,168.734709,-45.016313,168.734738,NaN,NaN,0.95,33.0,31.26,NaN,-2867988.026701,NaN,-2867989.302988
6,2019-01-15 05:17:09+00:00,-45.016305,168.734746,-45.015313,168.735276,NaN,NaN,6.05,34.0,205.57,NaN,-2867988.790337,NaN,-2867925.590129
7,2019-01-15 05:22:09+00:00,-45.015282,168.735262,-45.015357,168.735276,NaN,NaN,1.66,300.0,499.41,NaN,-2867923.614288,NaN,-2867928.393687
8,2019-01-15 05:23:50+00:00,-45.015349,168.735271,-45.016257,168.734693,NaN,NaN,6.08,101.0,614.57,NaN,-2867927.886377,NaN,-2867985.735794
9,2019-01-15 05:24:21+00:00,-45.016302,168.734716,-45.016298,168.734732,NaN,NaN,1.09,31.0,33.77,NaN,-2867988.598093,NaN,-2867988.347108
10,2019-01-15 05:24:55+00:00,-45.016305,168.734745,-45.015293,168.735269,NaN,NaN,6.04,34.0,205.39,NaN,-2867988.790337,NaN,-2867924.319183
11,2019-01-15 05:56:36+00:00,-45.015269,168.735261,-45.015901,168.735709,NaN,NaN,1.78,1901.0,3387.58,NaN,-2867922.786571,NaN,-2867963.051005