## Initial Setup

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from tools import *
import pandas as pd
import numpy as np
import datetime as dt

In [3]:
def add_laps(s1, s2):
    new_lap = s2.copy()
    new_lap.start_pos_lat  = s1.start_pos_lat
    new_lap.start_pos_long = s1.start_pos_long
    new_lap.lap_time = s1.lap_time + s2.lap_time
    new_lap.lap_distance = s1.lap_distance + s2.lap_distance
    new_lap.avg_speed = new_lap.lap_distance / new_lap.lap_time
    new_lap.start_x = s1.start_x
    new_lap.start_y = s1.start_y

    return new_lap

# add_laps(laps.iloc[9], laps.iloc[10])

In [4]:
activities = pd.read_csv("data/activities.csv")[["Activity ID", "Activity Date", "Activity Name", "IS_TRACK_WORKOUT", 
                                                 "HAS_ACCURATE_LAPS", "Activity Type", "Activity Description", "Elapsed Time", 
                                                 "Distance", "Max Heart Rate", "Filename", "Elapsed Time.1", "Moving Time",
                                                 "Distance.1", "Max Speed", "Average Speed", "Elevation Gain"]]
activities = activities.assign(New_Filename=lambda x: x.Filename.str[:-3])
activities[(activities.HAS_ACCURATE_LAPS == 0.5) | (activities.HAS_ACCURATE_LAPS == 1.0)]

,Activity ID,Activity Date,Activity Name,IS_TRACK_WORKOUT,HAS_ACCURATE_LAPS,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,Filename,Elapsed Time.1,Moving Time,Distance.1,Max Speed,Average Speed,Elevation Gain,New_Filename
825,2147844352,"Feb 12, 2019, 3:14:17 AM",Track session,1.0,1.0,Run,"3*(600m then 200m with 30 second rest), 1:44, ...",4275,8.03,189.0,activities/2289237041.fit.gz,4275.0,4218.0,8029.600098,8.200000,NaN,57.048492,activities/2289237041.fit
827,2147845716,"Feb 14, 2019, 4:09:26 AM",Track session,1.0,1.0,Run,"5*300m (47,50,49,47,45) then 6*200m (28,30,28,...",3763,9.04,188.0,activities/2289237057.fit.gz,3763.0,2924.0,9046.099609,8.800000,NaN,64.230118,activities/2289237057.fit
830,2159452990,"Feb 16, 2019, 11:50:55 PM",800m Southland Club Champs,1.0,1.0,Run,"2:07, still very windy",5988,7.95,164.0,activities/2302289075.fit.gz,5988.0,2701.0,7953.200195,9.000000,NaN,0.000000,activities/2302289075.fit
836,2164067134,"Feb 21, 2019, 4:07:26 AM",Track session,1.0,0.5,Run,"12 min tempo at 3:40 pace, then 4*90sec interv...",3779,9.99,200.0,activities/2307063824.fit.gz,3779.0,2654.0,9992.799805,7.100000,NaN,71.410820,activities/2307063824.fit
839,2175885669,"Feb 26, 2019, 3:04:35 AM",Track session,1.0,1.0,Run,"600m, 3*300m then 3*200m at 1:31, 44, 44, 44, ...",4705,9.79,167.0,activities/2319257689.fit.gz,4705.0,3178.0,9798.900391,9.400000,NaN,70.395714,activities/2319257689.fit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2052,8408655136,"Jan 17, 2023, 7:39:56 PM",Track,1.0,1.0,Run,400’s at 63,4249,9.49,187.0,activities/9020005768.fit.gz,4249.0,3401.0,9498.209961,8.454004,2.792770,227.006668,activities/9020005768.fit
2054,8416098869,"Jan 19, 2023, 7:41:15 AM",200’s,1.0,1.0,Run,NaN,3855,10.10,189.0,activities/9028217372.fit.gz,3855.0,3173.0,10102.100586,8.332031,3.183769,350.115692,activities/9028217372.fit
2059,8446286759,"Jan 24, 2023, 7:43:37 PM",600’s,1.0,1.0,Run,Not so good,4037,7.84,182.0,activities/9061708304.fit.gz,4037.0,3099.0,7839.490234,8.178027,2.529684,172.842377,activities/9061708304.fit
2073,8522903907,"Feb 7, 2023, 7:40:09 PM",200’s,1.0,1.0,Run,NaN,3479,8.22,187.0,activities/9147956833.fit.gz,3479.0,2947.0,8225.610352,8.212011,2.791181,205.572403,activities/9147956833.fit
2085,8594860256,"Feb 20, 2023, 7:38:08 PM",200’s,1.0,1.0,Run,NaN,3667,8.09,181.0,activities/9227237528.fit.gz,3667.0,3419.0,8091.510254,8.048340,2.366631,7.940000,activities/9227237528.fit

In [5]:
laps_to_fix = activities[activities.HAS_ACCURATE_LAPS == 0.5].reset_index(drop=True)
laps_to_fix

,Activity ID,Activity Date,Activity Name,IS_TRACK_WORKOUT,HAS_ACCURATE_LAPS,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,Filename,Elapsed Time.1,Moving Time,Distance.1,Max Speed,Average Speed,Elevation Gain,New_Filename
0,2164067134,"Feb 21, 2019, 4:07:26 AM",Track session,1.0,0.5,Run,"12 min tempo at 3:40 pace, then 4*90sec interv...",3779,9.99,200.0,activities/2307063824.fit.gz,3779.0,2654.0,9992.799805,7.100000,NaN,71.410820,activities/2307063824.fit
1,2686254553,"Sep 3, 2019, 4:02:12 AM",Track session,1.0,0.5,Run,"10 * 400m at 75s (73,72,69 for last few though)",4194,9.77,182.0,activities/2848431475.fit.gz,4194.0,2670.0,9778.599609,7.400000,NaN,172.000000,activities/2848431475.fit
2,2740607691,"Sep 24, 2019, 4:07:43 AM",Track session,1.0,0.5,Run,"3 min, 4 min, 2.5min, 4min, 3min at 75 a lap",4724,10.04,161.0,activities/2904836587.fit.gz,4724.0,2652.0,10041.500000,7.000000,NaN,119.000000,activities/2904836587.fit
3,2753600222,"Oct 1, 2019, 2:57:58 AM",Track Session,1.0,0.5,Run,"2 * (300m, 3*400m). Good fun",6099,11.04,184.0,activities/2918394967.fit.gz,6099.0,3305.0,11041.599609,8.300000,NaN,210.000000,activities/2918394967.fit
4,2794977425,"Oct 17, 2019, 3:02:27 AM",Track Session,1.0,0.5,Run,"Speed ladder, 50m to 200m and back down in 50m...",4968,7.13,183.0,activities/2961822655.fit.gz,4968.0,2479.0,7135.399902,9.300000,NaN,89.000000,activities/2961822655.fit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,7799845633,"Sep 13, 2022, 5:41:24 AM",Session,1.0,0.5,Run,NaN,4810,12.88,188.0,activities/8331789300.fit.gz,4810.0,4406.0,12879.360352,7.797949,2.923141,8.526191,activities/8331789300.fit
60,8213671236,"Dec 6, 2022, 7:28:51 AM",Getting dizzy,1.0,0.5,Run,"4*5*400, 68-71s. Felt pretty good for running ...",6507,20.00,190.0,activities/8800228183.fit.gz,6507.0,6373.0,20003.470703,8.027979,3.138784,401.269470,activities/8800228183.fit
61,8242568393,"Dec 13, 2022, 6:38:12 AM",Dizzy track,1.0,0.5,Run,"4*5*300m, featuring 550m of elevation",6418,16.26,189.0,activities/8833282441.fit.gz,6418.0,5002.0,16267.109375,7.321973,3.252121,551.389709,activities/8833282441.fit
62,8269499915,"Dec 20, 2022, 6:58:23 AM",Track,1.0,0.5,Run,"15*400, less recovery and faster than 2 weeks ago",5972,15.79,189.0,activities/8863626793.fit.gz,5972.0,4627.0,15790.190430,7.308008,3.412620,487.673370,activities/8863626793.fit
63,8344043484,"Jan 5, 2023, 7:41:38 PM",Soggy track,1.0,0.5,Run,"6*200 at 29, 200m jog recovery",2831,9.41,183.0,activities/8948079145.fit.gz,2831.0,2783.0,9418.650391,8.101954,3.384351,301.180237,activities/8948079145.fit

### Inspect Workout

In [25]:
index = 3

activity = laps_to_fix.iloc[index]
filename = "data/" + activity.Filename[:-3]
print(activity)

points, laps = read_activity(filename)
laps

Activity ID                               2753600222
Activity Date                Oct 1, 2019, 2:57:58 AM
Activity Name                          Track Session
IS_TRACK_WORKOUT                                 1.0
HAS_ACCURATE_LAPS                                0.5
Activity Type                                    Run
Activity Description    2 * (300m, 3*400m). Good fun
Elapsed Time                                    6099
Distance                                       11.04
Max Heart Rate                                 184.0
Filename                activities/2918394967.fit.gz
Elapsed Time.1                                6099.0
Moving Time                                   3305.0
Distance.1                              11041.599609
Max Speed                                        8.3
Average Speed                                    NaN
Elevation Gain                                 210.0
New_Filename               activities/2918394967.fit
Name: 3, dtype: object

,Timestamp,start_pos_lat,start_pos_long,end_pos_lat,end_pos_long,total_timer_time,total_distance,avg_speed,lap_time,lap_distance,start_x,start_y,end_x,end_y
0,2019-10-01 03:38:24+00:00,-45.012725,168.742717,-45.015336,168.735186,NaN,NaN,1.554,2425.160,3768.10,10862642.981715,-4588417.159836,10862158.199118,-4588683.3024
1,2019-10-01 03:49:41+00:00,-45.015336,168.735187,-45.015402,168.734324,NaN,NaN,0.869,677.527,588.56,10862158.24768,-4588683.24259,10862102.676686,-4588690.043755
2,2019-10-01 03:50:31+00:00,-45.015406,168.734322,-45.015321,168.735248,NaN,NaN,6.325,49.694,314.33,10862102.590354,-4588690.376978,10862162.191985,-4588681.781536
3,2019-10-01 03:51:44+00:00,-45.015321,168.735248,-45.015359,168.735212,NaN,NaN,0.707,72.726,51.43,10862162.191985,-4588681.781536,10862159.877201,-4588685.617872
4,2019-10-01 03:54:35+00:00,-45.015348,168.735215,-45.015357,168.735215,NaN,NaN,2.82,171.446,483.54,10862160.033679,-4588684.524217,10862160.049866,-4588685.446988
5,2019-10-01 03:55:42+00:00,-45.015351,168.735214,-45.015362,168.735265,NaN,NaN,6.217,66.755,414.99,10862159.968929,-4588684.840351,10862163.249555,-4588685.891285
6,2019-10-01 03:57:25+00:00,-45.01531,168.735241,-45.015361,168.735216,NaN,NaN,0.639,102.957,65.79,10862161.695575,-4588680.679337,10862160.114615,-4588685.874197
7,2019-10-01 03:58:30+00:00,-45.015352,168.735214,-45.015349,168.7353,NaN,NaN,6.484,65.384,423.92,10862159.963534,-4588684.917249,10862165.531964,-4588684.584026
8,2019-10-01 04:11:24+00:00,-45.015302,168.735271,-45.015415,168.734316,NaN,NaN,1.812,774.230,1402.75,10862163.681216,-4588679.799287,10862102.164088,-4588691.351014
9,2019-10-01 04:12:12+00:00,-45.015413,168.734317,-45.015373,168.735269,NaN,NaN,6.542,47.232,308.99,10862102.245025,-4588691.111777,10862163.546322,-4588687.053293
10,2019-10-01 04:13:41+00:00,-45.015323,168.735241,-45.01533,168.73524,NaN,NaN,0.646,89.144,57.60,10862161.727949,-4588682.012229,10862161.657804,-4588682.644498
11,2019-10-01 04:14:46+00:00,-45.015322,168.735238,-45.015431,168.735298,NaN,NaN,6.259,65.376,409.18,10862161.517514,-4588681.824257,10862165.39707,-4588693.008585
12,2019-10-01 04:16:42+00:00,-45.015379,168.735274,-45.015359,168.73523,NaN,NaN,0.586,115.445,67.70,10862163.864672,-4588687.625753,10862161.042687,-4588685.592239
13,2019-10-01 04:17:49+00:00,-45.015349,168.735227,-45.015353,168.735305,NaN,NaN,6.153,66.866,411.41,10862160.794482,-4588684.635291,10862165.850314,-4588685.019779
14,2019-10-01 04:19:52+00:00,-45.015305,168.735282,-45.015367,168.735232,NaN,NaN,0.518,123.006,63.67,10862164.388062,-4588680.123966,10862161.123623,-4588686.446657
15,2019-10-01 04:20:53+00:00,-45.015352,168.735223,-45.015403,168.735364,NaN,NaN,6.691,61.377,410.68,10862160.540881,-4588684.934337,10862169.627351,-4588690.077932
16,2019-10-01 04:39:39+00:00,-45.015342,168.735335,-45.015965,168.735701,NaN,NaN,1.603,1124.022,1801.37,10862167.771207,-4588683.891948,10862191.312934,-4588747.434991

In [26]:
new_points = (
    points
    [(points.Timestamp < pd.Timestamp("2019-10-01 03:51:44+00:00")) | (points.Timestamp > pd.Timestamp("2019-10-01 03:54:35+00:00"))]
)
new_points

,Timestamp,lat,long,speed,cadence,x,y
0,2019-10-01 02:57:58+00:00,-45.012725,168.742717,3.088,180.0,10862642.981715,-4588417.159836
1,2019-10-01 02:58:06+00:00,-45.012634,168.742789,1.222,180.0,10862647.611283,-4588407.829595
2,2019-10-01 02:58:10+00:00,-45.012604,168.74277,1.129,119.0,10862646.364861,-4588404.796412
3,2019-10-01 02:58:17+00:00,-45.012596,168.742776,0.019,0.0,10862646.78573,-4588404.010348
4,2019-10-01 02:58:21+00:00,-45.012536,168.742794,1.838,0.0,10862647.962007,-4588397.824364
...,...,...,...,...,...,...,...
1081,2019-10-01 04:39:09+00:00,-45.01596,168.735702,0.009,117.0,10862191.399266,-4588746.853987
1082,2019-10-01 04:39:15+00:00,-45.015962,168.735705,0.019,0.0,10862191.604306,-4588747.059047
1083,2019-10-01 04:39:20+00:00,-45.015963,168.735701,0.019,0.0,10862191.329121,-4588747.18721
1084,2019-10-01 04:39:33+00:00,-45.015965,168.735698,0.019,0.0,10862191.124082,-4588747.400814
1085,2019-10-01 04:39:37+00:00,-45.015965,168.735701,0.028,0.0,10862191.312934,-4588747.434991

In [27]:
laps.iloc[2] = add_laps(laps.iloc[1], laps.iloc[2])
new_laps = laps.drop([1, 4]).reset_index(drop=True)
new_laps

,Timestamp,start_pos_lat,start_pos_long,end_pos_lat,end_pos_long,total_timer_time,total_distance,avg_speed,lap_time,lap_distance,start_x,start_y,end_x,end_y
0,2019-10-01 03:38:24+00:00,-45.012725,168.742717,-45.015336,168.735186,NaN,NaN,1.554,2425.160,3768.10,10862642.981715,-4588417.159836,10862158.199118,-4588683.3024
1,2019-10-01 03:50:31+00:00,-45.015336,168.735187,-45.015321,168.735248,NaN,NaN,1.241562,727.221,902.89,10862158.24768,-4588683.24259,10862162.191985,-4588681.781536
2,2019-10-01 03:51:44+00:00,-45.015321,168.735248,-45.015359,168.735212,NaN,NaN,0.707,72.726,51.43,10862162.191985,-4588681.781536,10862159.877201,-4588685.617872
3,2019-10-01 03:55:42+00:00,-45.015351,168.735214,-45.015362,168.735265,NaN,NaN,6.217,66.755,414.99,10862159.968929,-4588684.840351,10862163.249555,-4588685.891285
4,2019-10-01 03:57:25+00:00,-45.01531,168.735241,-45.015361,168.735216,NaN,NaN,0.639,102.957,65.79,10862161.695575,-4588680.679337,10862160.114615,-4588685.874197
5,2019-10-01 03:58:30+00:00,-45.015352,168.735214,-45.015349,168.7353,NaN,NaN,6.484,65.384,423.92,10862159.963534,-4588684.917249,10862165.531964,-4588684.584026
6,2019-10-01 04:11:24+00:00,-45.015302,168.735271,-45.015415,168.734316,NaN,NaN,1.812,774.230,1402.75,10862163.681216,-4588679.799287,10862102.164088,-4588691.351014
7,2019-10-01 04:12:12+00:00,-45.015413,168.734317,-45.015373,168.735269,NaN,NaN,6.542,47.232,308.99,10862102.245025,-4588691.111777,10862163.546322,-4588687.053293
8,2019-10-01 04:13:41+00:00,-45.015323,168.735241,-45.01533,168.73524,NaN,NaN,0.646,89.144,57.60,10862161.727949,-4588682.012229,10862161.657804,-4588682.644498
9,2019-10-01 04:14:46+00:00,-45.015322,168.735238,-45.015431,168.735298,NaN,NaN,6.259,65.376,409.18,10862161.517514,-4588681.824257,10862165.39707,-4588693.008585
10,2019-10-01 04:16:42+00:00,-45.015379,168.735274,-45.015359,168.73523,NaN,NaN,0.586,115.445,67.70,10862163.864672,-4588687.625753,10862161.042687,-4588685.592239
11,2019-10-01 04:17:49+00:00,-45.015349,168.735227,-45.015353,168.735305,NaN,NaN,6.153,66.866,411.41,10862160.794482,-4588684.635291,10862165.850314,-4588685.019779
12,2019-10-01 04:19:52+00:00,-45.015305,168.735282,-45.015367,168.735232,NaN,NaN,0.518,123.006,63.67,10862164.388062,-4588680.123966,10862161.123623,-4588686.446657
13,2019-10-01 04:20:53+00:00,-45.015352,168.735223,-45.015403,168.735364,NaN,NaN,6.691,61.377,410.68,10862160.540881,-4588684.934337,10862169.627351,-4588690.077932
14,2019-10-01 04:39:39+00:00,-45.015342,168.735335,-45.015965,168.735701,NaN,NaN,1.603,1124.022,1801.37,10862167.771207,-4588683.891948,10862191.312934,-4588747.434991

In [28]:
new_points.Timestamp = pd.to_datetime(new_points.Timestamp)
new_points.Timestamp = new_points.Timestamp.dt.tz_localize(None)

new_laps.Timestamp = pd.to_datetime(new_laps.Timestamp)
new_laps.Timestamp = new_laps.Timestamp.dt.tz_localize(None)

/tmp/ipykernel_4623/3947062326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_points.Timestamp = pd.to_datetime(new_points.Timestamp)
/tmp/ipykernel_4623/3947062326.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_points.Timestamp = new_points.Timestamp.dt.tz_localize(None)

In [29]:
with pd.ExcelWriter(filename[:-4] + '.xlsx') as writer:
    new_points.to_excel(writer, sheet_name='points', index=False)
    new_laps.to_excel(writer, sheet_name='laps', index=False)

# read_activity(filename[:-4] + '.xlsx')

### Save work

In [30]:
activities.loc[activities['Activity ID'] == activity['Activity ID'], ['New_Filename']] = filename[:-4] + '.xlsx'
activities.loc[activities['Activity ID'] == activity['Activity ID'], ['HAS_ACCURATE_LAPS']] = 1
activities.to_csv("data/activities.csv", index=False)